### ISSUE TITLE
error message for the last few days

### ISSUE THREAD

**Issue by ARG12345** [120Studio/120home#11]
graph.instagram.com/logging_client_events:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/ajax/bz:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/logging/falco:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 The resource https://www.instagram.com/graphql/query/?query_hash=24a36f49b32dea22e33c2e6e35bad4d3&variables=%7B%22only_stories%22%3Atrue%2C%22stories_prefetch%22%3Atrue%2C%22stories_video_dash_manifest%22%3Afalse%7D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
(index):1 The resource https://www.instagram.com/graphql/query/?query_hash=ed2e3ff5ae8b96717476b62ef06ed8cc&variables=%7B%22fetch_media_count%22%3A0%2C%22fetch_suggested_count%22%3A30%2C%22ignore_cache%22%3Atrue%2C%22filter_followed_friends%22%3Atrue%2C%22seen_ids%22%3A%5B%5D%2C%22include_reel%22%3Atrue%7D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
(index):1 The resource https://www.instagram.com/static/bundles/es6/FeedSidebarContainer.css/5c0e5c506162.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
graph.instagram.com/logging_client_events:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/ajax/bz:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/logging/falco:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
graph.instagram.com/logging_client_events:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2/ajax/bz:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load SourceMap: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
37122a5b2d59.js:81 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT
n.send @ 37122a5b2d59.js:81
h @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:81
n.map @ 37122a5b2d59.js:81
map @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:74
p @ 37122a5b2d59.js:74
c @ 37122a5b2d59.js:74
e.post @ 37122a5b2d59.js:74
e.send @ 37122a5b2d59.js:88
send @ 37122a5b2d59.js:87
u @ 37122a5b2d59.js:86
i.guard.isContinuation @ 37122a5b2d59.js:86
37122a5b2d59.js:81 POST https://www.instagram.com/ajax/bz net::ERR_BLOCKED_BY_CLIENT
n.send @ 37122a5b2d59.js:81
h @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:81
n.map @ 37122a5b2d59.js:81
map @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:74
p @ 37122a5b2d59.js:74
c @ 37122a5b2d59.js:74
e.post @ 37122a5b2d59.js:74
send @ 37122a5b2d59.js:87
u @ 37122a5b2d59.js:86
i.guard.isContinuation @ 37122a5b2d59.js:86
setTimeout (async)
s @ 37122a5b2d59.js:86
u @ 37122a5b2d59.js:86
i.guard.isContinuation @ 37122a5b2d59.js:86
37122a5b2d59.js:81 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT
n.send @ 37122a5b2d59.js:81
h @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:81
n.map @ 37122a5b2d59.js:81
map @ 37122a5b2d59.js:81
(anonymous) @ 37122a5b2d59.js:74
p @ 37122a5b2d59.js:74
c @ 37122a5b2d59.js:74
e.post @ 37122a5b2d59.js:74
e.send @ 37122a5b2d59.js:88
send @ 37122a5b2d59.js:87
u @ 37122a5b2d59.js:86
i.guard.isContinuation @ 37122a5b2d59.js:86
setTimeout (async)
s @ 37122a5b2d59.js:86
h @ 37122a5b2d59.js:86
v @ b97d39b303ac.js:31
37122a5b2d59.js:87 POST https://www.instagram.com/ajax/bz net::ERR_BLOCKED_BY_CLIENT
sendWithBeacon @ 37122a5b2d59.js:87
c @ 37122a5b2d59.js:86
(anonymous) @ 37122a5b2d59.js:86
v @ b97d39b303ac.js:31
37122a5b2d59.js:81 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT

**Comment by linweigao** [comment]
Thank you for your feedback.

It looks like you have some network blocker extension, for example, ad blocker.
This is not caused by our extension for sure.
