### ISSUE TITLE
(No) Text Wrapping in DMs

### ISSUE THREAD

**Issue by the-argent** [120Studio/120home#12]
Description: When I have **Extension for Instagram** on, my DMs stop wrapping across multiple lines. The only extension features I have turned on are **Image/Video download** and **Clickable links**. See screenshots below.
Extension Version: 1.0.21
Chrome browser version:  87.0.4280.141 (Official Build) (64-bit)
OS: Windows 10 Version 2004 (OS Build 21277.1000)

With the extension ON
![image](https://user-images.githubusercontent.com/1126644/104057239-6f1d7a80-51b7-11eb-8f5f-c732e4bacfe7.png)

With the extension OFF
![image](https://user-images.githubusercontent.com/1126644/104057287-8197b400-51b7-11eb-9833-da46d672522d.png)

**Comment by linweigao** [comment]
Thank you for contacting us. We will work on this investigation.

**Comment by linweigao** [comment]
Fixed.

**Comment by the-argent** [comment]
Confirmed that it works for me 👍
