### ISSUE TITLE
Video Player DOESN'T WORK

### ISSUE THREAD

**Issue by JetixEdits** [120Studio/120home#14]
Recently today I can't use the video player feature anymore. 
![issue](https://user-images.githubusercontent.com/82558317/114809061-74bacb80-9d77-11eb-9b72-0c974a1efbdd.PNG)

**Comment by linweigao** [comment]
Thank you for reporting this issue. We are working on a fix.

**Comment by linweigao** [comment]
Thank you for letting us know this issue. The fix has been submitted for Google for review. It may take weeks for you to get it.
