### ISSUE TITLE
add story need to rotate device (laptop)

### ISSUE THREAD

**Issue by Dhanamerdeka** [120Studio/120home#15]
Can you fix this?

**Comment by linweigao** [comment]
Thank you for reporting this issue. "Add story" feature is experimental. We noticed the same issue as you have to rotate the device. Unfortunately it is very hard to simulate the device rotation.

To work around, you may want to use Chrome "Developer tools" to simulate the rotation.

**Comment by linweigao** [comment]
Thank you for reporting this issue. I add a fix for that, it works on my device. You may want to have a try.

But there is still some limitations, no video uploading, no dragging and dropping. I am still investigating to see whether it can be improved.

**Comment by Dhanamerdeka** [comment]
thanks alot
i hope you can fix that
