### ISSUE TITLE
looking for the admin

### ISSUE THREAD

**Issue by RaeAtBiscience** [120Studio/120home#22]
Hello there, we are BIScience (founders of AdClarity, GeoSurf and UrbanVPN).
We’re looking for a partnership with your App or Extension - sell us your anonymised clickstream data and we will provide you with monthly revenue for it.

We follow all Data protection laws and guidelines.

Looking forward to hearing back,
Rae
raeATbiscienceDOTcom

**Comment by linweigao** [comment]
Thank you for contacting us. We don't have plan to collect any data so far. This is what we committed to all users of this extension.
