### ISSUE TITLE
Can't open modal for options in "desktop mode"

### ISSUE THREAD

**Issue by frasurf** [120Studio/120home#25]
Hi,
once I disable the "Mobile Layout", the extension icon in the upper right corner disappears and there's no way to open the option modal.
Basically the element "instagram-web-option-modal" stays with "display:none", and the element "instagram-ext-options" is no longer present in the page.

Even if I click on the extension icon in the browser menu, nothing happens.

thanks

**Comment by linweigao** [comment]
Thank you for contacting us. We can repro this issue and working on a fix.

**Comment by linweigao** [comment]
Fix is submitted to Google. It should be approved by 2-3 days.
