### ISSUE TITLE
in the story impossible to read the videos on the button is on the right

### ISSUE THREAD

**Issue by cmdcirdec** [120Studio/120home#5]
as the screenshot shows, the play button for a story does not work. it is on the right and more in the center and not clickable.
It would also be good if the story reads the videos automatically. I activated the auto video miniplayer but it didn't change anything.
![Annotation 2020-04-04 214748](https://user-images.githubusercontent.com/5289783/78460066-051ef480-76be-11ea-85e2-059fbb7ffbc2.png)

**Comment by linweigao** [comment]
Thank you for contacting us. We will investigate this.

**Comment by linweigao** [comment]
It seems no longer to be an issue. Close it now.
