### ISSUE TITLE
Not blocking login demand for school's photos

### ISSUE THREAD

**Issue by jelabarre59** [120Studio/120home#9]
I've tried this extension in Brave, and the site INSIsTS on my login just about as fast as if I were viewing without the extension.  So Instagram must have found a way to block you.  (I do not nor will I ever have an Instagram account).

https://www.instagram.com/pawlingcsd/

**Comment by linweigao** [comment]
Thank you for contacting us. I was able to view your profile by using my extension. I don't see any issues. I am not clear about site INSIsTS. Could you provide more details about the issue?

**Comment by jelabarre59** [comment]
It's been a couple months since I tried this, I don't even remember what was happening with it by now.
